In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [6]:
X,y = load_iris().data, load_iris().target

In [7]:
X = X[:100,:]

In [10]:
y = y.reshape(-1,1)[:100,:]

In [11]:
X.shape, y.shape

((100, 4), (100, 1))

In [36]:
class nn_sigmoid(object):
    def __init__(self, learning_ratio =0.005,iterations = 1000):
        self.learning_ratio = learning_ratio
        self.iterations = iterations
        
    def fit(self,X,y):
        costs = []
        w_ = np.zeros((X.shape[1],1))
        b_ = 0
        m_ = X.shape[0]
        for i in range(self.iterations):
            z = np.dot(X,w_) + b_
            a = self.sigmoid(z)
            cost = -(1/m_)* np.sum(y * np.log(a) + (1-y)*np.log(1-a))
            dw = (1/m_) * np.dot(X.T,(a-y))
            db = (1/m_) * np.sum(a-y)
            cost = np.squeeze(np.array(cost))
            w_ -= self.learning_ratio * dw
            b_ -= self.learning_ratio * db
            if i % 100 == 0:
                costs.append(cost)
                acc = self.acc(y,np.where(a>0.5,1,0),m_)
                print(f'{i} epochs: cost: {cost} acc: {acc}')
        return w_, b_, costs
        
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def acc(self,y_true,y_pred,m):
        return np.sum(y_true == y_pred)/m

In [37]:
w_, b_, costs = nn_sigmoid().fit(X,y)

0 epochs: cost: 0.6931471805599453 acc: 0.5
100 epochs: cost: 0.5055281998488886 acc: 1.0
200 epochs: cost: 0.39071489187553554 acc: 1.0
300 epochs: cost: 0.31435473505864087 acc: 1.0
400 epochs: cost: 0.261161063774983 acc: 1.0
500 epochs: cost: 0.2225089241145809 acc: 1.0
600 epochs: cost: 0.19339406101203982 acc: 1.0
700 epochs: cost: 0.17079311322170226 acc: 1.0
800 epochs: cost: 0.15280236724736612 acc: 1.0
900 epochs: cost: 0.13817632818260628 acc: 1.0


In [38]:
w_

array([[-0.20242447],
       [-0.77341487],
       [ 1.18499875],
       [ 0.50433349]])

In [39]:
b_

-0.13300697356214528

In [40]:
## lets go step by step

In [41]:
w_ = np.zeros((X.shape[1],1))
w_

array([[0.],
       [0.],
       [0.],
       [0.]])

In [42]:
b_ = 0

In [43]:
m_ = X.shape[0]
m_

100

In [44]:
z = np.dot(X,w_) + b_
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [50]:
a = 1 / (1+np.exp(-z))
a

array([[0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
      

In [51]:
cost = -(1/m_)* np.sum(y * np.log(a) + (1-y)*np.log(1-a))
cost

0.6931471805599453

In [52]:
dw = (1/m_) * np.dot(X.T,(a-y))
dw         

array([[-0.2325],
       [ 0.1645],
       [-0.6995],
       [-0.27  ]])

In [53]:
db = (1/m_) * np.sum(a-y)
db 

0.0

In [54]:
cost = np.squeeze(np.array(cost))
cost

array(0.69314718)

In [56]:
w_ -= 0.005 * dw
w_

array([[ 0.0011625],
       [-0.0008225],
       [ 0.0034975],
       [ 0.00135  ]])

In [57]:
b_ -= 0.005 * db
b_

0.0